language: csharp
os:
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
# Ensure that .NET Core is installed
dotnet: 1.0.4
# Ensure that Mono is not installed
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - chmod +x ./build.sh && ./build.sh

deploy:
 skip_cleanup: true
 provider: script
 script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $TRAVIS_BUILD_NUMBER
 on:
   branch: master